name: pnpm CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        run_install: pnpm install
        
    - run: pnpm build
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ueg-card-vue
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist
